name: flt_cli
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/vaisakhferoke/flt_cli


environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
executables:
  flt_cli: flt_cli
